-- CreateEnum
CREATE TYPE "TYPES" AS ENUM ('EXPANSE', 'INCOME');

-- CreateEnum
CREATE TYPE "RECURRENCEINTERVAL" AS ENUM ('DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY');

-- CreateEnum
CREATE TYPE "PAYMENTMETHOD" AS ENUM ('CARD', 'BANK_TRANSFER', 'MOBILE_PAYMENT');

-- AlterTable
ALTER TABLE "Transaction" ADD COLUMN     "isRecurring" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "paymentMethod" "PAYMENTMETHOD",
ADD COLUMN     "receiptUrl" TEXT,
ADD COLUMN     "recurrenceInterval" "RECURRENCEINTERVAL";
